server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG

# Database
spring:
  datasource:
    url: jdbc:oracle:thin:@10.110.15.57/PLMDEV2 #jdbc:postgresql://localhost:5432/springboot
    username: wcadmin #postgres
    password: wcadmin #1234
    driver-class-name: oracle.jdbc.driver.OracleDriver #org.postgresql.Driver

  # JPA
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true